import nodemailer from 'nodemailer';

// SendGrid SMTP configuration with API key authentication
const transporter = nodemailer.createTransport({
  service: 'SendGrid',
  auth: {
    user: 'apikey', // required literal for SendGrid
    pass: process.env.SENDGRID_API_KEY,
  },
});

// Enhanced logging for SendGrid responses
function logEmailResult(operation: string, result: any, error?: any) {
  const timestamp = new Date().toISOString();
  if (error) {
    console.error(`[${timestamp}] SendGrid ${operation} FAILED:`, {
      error: error.message,
      code: error.code,
      statusCode: error.statusCode,
      responseBody: error.response?.body
    });
  } else {
    console.log(`[${timestamp}] SendGrid ${operation} SUCCESS:`, {
      messageId: result.messageId,
      response: result.response,
      accepted: result.accepted,
      rejected: result.rejected
    });
  }
}

export async function sendWebhookFailureEmail({
  eventId,
  eventType,
  customerEmail,
  error,
  attemptCount = 1,
}: {
  eventId: string;
  eventType: string;
  customerEmail: string;
  error: string;
  attemptCount?: number;
}) {
  try {
    const mailOptions = {
      from: '"OnyxHooks & More™ Team" <info@onyxnpearls.com>',
      replyTo: 'info@onyxnpearls.com',
      to: process.env.ALERT_EMAIL || 'admin@onyxnpearls.com',
      subject: `🚨 Webhook Failure Alert: ${eventType}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
          <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 8px 8px 0 0;">
            <h2 style="margin: 0; font-size: 24px;">🚨 Webhook Processing Failed</h2>
            <p style="margin: 5px 0 0 0; opacity: 0.9;">OnyxHooks & More™ Alert System</p>
          </div>
          
          <div style="background: #f8f9fa; padding: 20px; border: 1px solid #e9ecef; border-top: none;">
            <h3 style="color: #dc3545; margin-top: 0;">Failure Details</h3>
            
            <table style="width: 100%; border-collapse: collapse; margin: 15px 0;">
              <tr style="background: white;">
                <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold; width: 30%;">Event ID:</td>
                <td style="padding: 12px; border: 1px solid #dee2e6; font-family: monospace;">${eventId}</td>
              </tr>
              <tr style="background: #f8f9fa;">
                <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Event Type:</td>
                <td style="padding: 12px; border: 1px solid #dee2e6;">${eventType}</td>
              </tr>
              <tr style="background: white;">
                <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Customer Email:</td>
                <td style="padding: 12px; border: 1px solid #dee2e6;">${customerEmail}</td>
              </tr>
              <tr style="background: #f8f9fa;">
                <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Attempt #:</td>
                <td style="padding: 12px; border: 1px solid #dee2e6;">${attemptCount}</td>
              </tr>
              <tr style="background: white;">
                <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Timestamp:</td>
                <td style="padding: 12px; border: 1px solid #dee2e6;">${new Date().toISOString()}</td>
              </tr>
            </table>
            
            <h4 style="color: #dc3545; margin: 20px 0 10px 0;">Error Message:</h4>
            <div style="background: #fff3cd; border: 1px solid #ffeaa7; border-radius: 4px; padding: 15px; font-family: monospace; color: #856404;">
              ${error}
            </div>
            
            <div style="margin-top: 20px; padding: 15px; background: #d1ecf1; border-left: 4px solid #17a2b8; border-radius: 4px;">
              <strong>Next Steps:</strong>
              <ul style="margin: 10px 0 0 0; padding-left: 20px;">
                <li>Check the admin dashboard Webhooks tab for retry options</li>
                <li>Verify Stripe webhook endpoint configuration</li>
                <li>Review customer subscription status if applicable</li>
              </ul>
            </div>
          </div>
          
          <div style="background: #e9ecef; padding: 15px; border-radius: 0 0 8px 8px; text-align: center; color: #6c757d; font-size: 12px;">
            <p style="margin: 0;">This alert was generated by OnyxHooks & More™ Webhook Monitoring System</p>
            <p style="margin: 5px 0 0 0;">Admin Dashboard: <a href="${process.env.NODE_ENV === 'production' ? 'https://onyxnpearls.com' : 'http://localhost:5000'}/admin">View Webhook Events</a></p>
          </div>
        </div>
      `,
    };

    const result = await transporter.sendMail(mailOptions);
    logEmailResult('webhook-failure-alert', result);
    console.log(`Webhook failure alert sent for event ${eventId}`);
    return { success: true, messageId: result.messageId };
  } catch (emailError) {
    logEmailResult('webhook-failure-alert', null, emailError);
    console.error('Failed to send webhook failure email:', emailError);
    return { success: false, error: (emailError as Error).message };
  }
}

export async function sendWebhookRecoveryEmail({
  eventId,
  eventType,
  customerEmail,
  originalAttempts,
}: {
  eventId: string;
  eventType: string;
  customerEmail: string;
  originalAttempts: number;
}) {
  try {
    const mailOptions = {
      from: '"OnyxHooks & More™ Team" <info@onyxnpearls.com>',
      replyTo: 'info@onyxnpearls.com',
      to: process.env.ALERT_EMAIL || 'admin@onyxnpearls.com',
      subject: `✅ Webhook Recovered: ${eventType}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
          <div style="background: linear-gradient(135deg, #28a745 0%, #20c997 100%); color: white; padding: 20px; border-radius: 8px 8px 0 0;">
            <h2 style="margin: 0; font-size: 24px;">✅ Webhook Successfully Recovered</h2>
            <p style="margin: 5px 0 0 0; opacity: 0.9;">OnyxHooks & More™ Recovery System</p>
          </div>
          
          <div style="background: #f8f9fa; padding: 20px; border: 1px solid #e9ecef; border-top: none;">
            <p style="color: #28a745; font-size: 16px; margin-top: 0;"><strong>Great news!</strong> A previously failed webhook has been successfully processed.</p>
            
            <table style="width: 100%; border-collapse: collapse; margin: 15px 0;">
              <tr style="background: white;">
                <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold; width: 30%;">Event ID:</td>
                <td style="padding: 12px; border: 1px solid #dee2e6; font-family: monospace;">${eventId}</td>
              </tr>
              <tr style="background: #f8f9fa;">
                <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Event Type:</td>
                <td style="padding: 12px; border: 1px solid #dee2e6;">${eventType}</td>
              </tr>
              <tr style="background: white;">
                <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Customer Email:</td>
                <td style="padding: 12px; border: 1px solid #dee2e6;">${customerEmail}</td>
              </tr>
              <tr style="background: #f8f9fa;">
                <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Previous Attempts:</td>
                <td style="padding: 12px; border: 1px solid #dee2e6;">${originalAttempts}</td>
              </tr>
              <tr style="background: white;">
                <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Recovered At:</td>
                <td style="padding: 12px; border: 1px solid #dee2e6;">${new Date().toISOString()}</td>
              </tr>
            </table>
          </div>
          
          <div style="background: #e9ecef; padding: 15px; border-radius: 0 0 8px 8px; text-align: center; color: #6c757d; font-size: 12px;">
            <p style="margin: 0;">Webhook monitoring is working correctly • OnyxHooks & More™</p>
          </div>
        </div>
      `,
    };

    const result = await transporter.sendMail(mailOptions);
    logEmailResult('webhook-recovery-alert', result);
    console.log(`Webhook recovery notification sent for event ${eventId}`);
    return { success: true, messageId: result.messageId };
  } catch (emailError) {
    logEmailResult('webhook-recovery-alert', null, emailError);
    console.error('Failed to send webhook recovery email:', emailError);
    return { success: false, error: (emailError as Error).message };
  }
}

// Send welcome email for new subscribers
export async function sendWelcomeEmail({
  recipientEmail,
  customerName,
  tier = 'starter'
}: {
  recipientEmail: string;
  customerName: string;
  tier?: string;
}) {
  try {
    const tierNames = {
      starter: 'Growth Starter',
      pro: 'Pro Operator', 
      vault: 'Vault Elite'
    };

    const tierName = tierNames[tier as keyof typeof tierNames] || 'Growth Starter';
    
    const mailOptions = {
      from: '"OnyxHooks & More™ Team" <info@onyxnpearls.com>',
      replyTo: 'info@onyxnpearls.com',
      to: recipientEmail,
      subject: `🎉 Welcome to OnyxHooks & More™ - Your ${tierName} Journey Begins!`,
      html: `
        <div style="max-width: 600px; margin: 0 auto; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; font-family: Arial, sans-serif;">
          <div style="padding: 40px 30px; text-align: center;">
            <h1 style="margin: 0 0 20px 0; font-size: 28px;">Welcome to OnyxHooks & More™!</h1>
            <div style="width: 120px; height: 120px; border-radius: 50%; border: 4px solid rgba(255,255,255,0.3); margin: 20px auto; background: rgba(255,255,255,0.1); display: flex; align-items: center; justify-content: center; font-size: 48px;">🎯</div>
            <h2 style="margin: 20px 0; color: #FFD700;">You're now a ${tierName}!</h2>
            <p style="font-size: 18px; line-height: 1.6; margin: 20px 0;">
              Congratulations ${customerName}! Your subscription is now active and you have full access to your ${tierName} features.
            </p>
            <div style="background: rgba(255,255,255,0.1); padding: 20px; border-radius: 10px; margin: 30px 0;">
              <h3 style="margin: 0 0 15px 0; color: #FFD700;">What's Next?</h3>
              <ul style="text-align: left; margin: 0; padding-left: 20px;">
                <li>Access your dashboard with unlimited hook generation</li>
                <li>Explore Pro Tools for advanced optimization</li>
                <li>Join the elite Council for AI-powered feedback</li>
                <li>Start building high-converting campaigns today</li>
              </ul>
            </div>
            <a href="https://2a4f613c-1b0c-4dab-90a9-79a7fe4a7759-00-221njkuiufget.picard.replit.dev/dashboard" style="display: inline-block; background: #FFD700; color: #333; padding: 15px 30px; text-decoration: none; border-radius: 25px; font-weight: bold; margin: 20px 0;">Access Your Dashboard</a>
            <p style="font-size: 14px; margin-top: 30px; opacity: 0.8;">
              Questions? Check our <a href="https://2a4f613c-1b0c-4dab-90a9-79a7fe4a7759-00-221njkuiufget.picard.replit.dev/faq" style="color: #FFD700;">FAQ page</a> or contact info@onyxnpearls.com<br>
              <strong>Since there's more to fishing than just hooks™</strong>
            </p>
            <div style="border-top: 1px solid rgba(255,255,255,0.2); padding-top: 20px; margin-top: 30px; text-align: center; color: rgba(255,255,255,0.6); font-size: 12px; line-height: 1.5;">
              <p style="margin: 0 0 10px 0;">You received this email because you're subscribed to OnyxHooks & More™ updates.</p>
              <p style="margin: 0;"><a href="/unsubscribe?email=${encodeURIComponent(recipientEmail)}&type=updates" style="color: rgba(255,255,255,0.6); text-decoration: underline;">Unsubscribe</a> | <a href="mailto:info@onyxnpearls.com" style="color: rgba(255,255,255,0.6); text-decoration: underline;">Contact Support</a></p>
              <p style="margin: 10px 0 0 0; font-size: 11px;">OnyxHooks & More™ by Onyx & Pearls Management, Inc. | This email was sent to ${recipientEmail}</p>
            </div>
          </div>
        </div>
      `,
      text: `Welcome to OnyxHooks & More™!

Congratulations ${customerName}! You're now a ${tierName} and your subscription is active.

Access your dashboard: https://2a4f613c-1b0c-4dab-90a9-79a7fe4a7759-00-221njkuiufget.picard.replit.dev/dashboard

Questions? Check our FAQ page: https://2a4f613c-1b0c-4dab-90a9-79a7fe4a7759-00-221njkuiufget.picard.replit.dev/faq or contact info@onyxnpearls.com

---
You received this email because you're subscribed to OnyxHooks & More™ updates.
Unsubscribe: ${process.env.REPLIT_DEV_DOMAIN || 'localhost:5000'}/unsubscribe?email=${encodeURIComponent(recipientEmail)}&type=updates
Contact Support: info@onyxnpearls.com
OnyxHooks & More™ by Onyx & Pearls Management, Inc. | This email was sent to ${recipientEmail}

Since there's more to fishing than just hooks™`
    };

    const result = await transporter.sendMail(mailOptions);
    logEmailResult('welcome-email', result);
    console.log('Welcome email sent successfully:', result.messageId);
    return { success: true, messageId: result.messageId };
  } catch (error) {
    logEmailResult('welcome-email', null, error);
    console.error('SendGrid Welcome Email Error:', error);
    return { success: false, error: (error as Error).message || 'Failed to send welcome email' };
  }
}

// Send NOS Challenge conversion notification
export async function sendNOSConversionEmail({
  recipientEmail,
  customerName,
  timeToGenerate,
  generatedHook,
  tier = 'free'
}: {
  recipientEmail: string;
  customerName: string;
  timeToGenerate: number;
  generatedHook: string;
  tier?: string;
}) {
  try {
    const mailOptions = {
      from: '"OnyxHooks & More™ Team" <info@onyxnpearls.com>',
      replyTo: 'info@onyxnpearls.com',
      to: recipientEmail,
      subject: `🏁 NOS Challenge Complete: ${timeToGenerate}s - Ready to Go Pro?`,
      html: `
        <div style="max-width: 600px; margin: 0 auto; background: linear-gradient(135deg, #ff6b35 0%, #f7931e 100%); color: white; font-family: Arial, sans-serif;">
          <div style="padding: 40px 30px; text-align: center;">
            <h1 style="margin: 0 0 20px 0; font-size: 28px;">🏁 NOS Challenge Complete!</h1>
            <div style="background: rgba(255,255,255,0.2); padding: 20px; border-radius: 15px; margin: 20px 0;">
              <h2 style="margin: 0; font-size: 48px; color: #FFD700;">${timeToGenerate}s</h2>
              <p style="margin: 10px 0 0 0; font-size: 16px;">Your Race Time</p>
            </div>
            <p style="font-size: 18px; line-height: 1.6; margin: 20px 0;">
              Outstanding ${customerName}! Your racing heritage is showing - that's championship-level speed.
            </p>
            <div style="background: rgba(255,255,255,0.1); padding: 20px; border-radius: 10px; margin: 30px 0; text-align: left;">
              <h3 style="margin: 0 0 15px 0; color: #FFD700; text-align: center;">Your Generated Hook:</h3>
              <p style="font-style: italic; background: rgba(0,0,0,0.2); padding: 15px; border-radius: 8px; margin: 0;">
                "${generatedHook}"
              </p>
            </div>
            <div style="background: rgba(255,255,255,0.1); padding: 20px; border-radius: 10px; margin: 30px 0;">
              <h3 style="margin: 0 0 15px 0; color: #FFD700;">Ready for Unlimited Runs?</h3>
              <p style="margin: 0 0 15px 0;">Upgrade to unlock:</p>
              <ul style="text-align: left; margin: 0; padding-left: 20px;">
                <li>Unlimited hook generation</li>
                <li>Advanced AI Council feedback</li>
                <li>Pro optimization tools</li>
                <li>Monthly leaderboard ranking</li>
              </ul>
            </div>
            <a href="https://2a4f613c-1b0c-4dab-90a9-79a7fe4a7759-00-221njkuiufget.picard.replit.dev/subscribe?plan=starter" style="display: inline-block; background: #FFD700; color: #333; padding: 15px 30px; text-decoration: none; border-radius: 25px; font-weight: bold; margin: 20px 0;">Upgrade to Starter ($47/month)</a>
            <p style="font-size: 14px; margin-top: 30px; opacity: 0.8;">
              Questions? Contact info@onyxnpearls.com<br>
              <strong>Since there's more to fishing than just hooks™</strong>
            </p>
          </div>
        </div>
      `,
      text: `🏁 NOS Challenge Complete: ${timeToGenerate}s

Outstanding ${customerName}! Your racing heritage is showing - that's championship-level speed.

Your Generated Hook: "${generatedHook}"

Ready for unlimited runs? Upgrade to unlock unlimited hook generation, advanced AI Council feedback, Pro optimization tools, and monthly leaderboard ranking.

Upgrade to Starter: https://2a4f613c-1b0c-4dab-90a9-79a7fe4a7759-00-221njkuiufget.picard.replit.dev/subscribe?plan=starter

Questions? Contact info@onyxnpearls.com

Since there's more to fishing than just hooks™`
    };

    const result = await transporter.sendMail(mailOptions);
    logEmailResult('nos-conversion-email', result);
    console.log('NOS conversion email sent successfully:', result.messageId);
    return { success: true, messageId: result.messageId };
  } catch (error) {
    logEmailResult('nos-conversion-email', null, error);
    console.error('SendGrid NOS Conversion Email Error:', error);
    return { success: false, error: (error as Error).message || 'Failed to send NOS conversion email' };
  }
}

// Send Vault tier confirmation email
export async function sendVaultConfirmationEmail({
  recipientEmail,
  customerName
}: {
  recipientEmail: string;
  customerName: string;
}) {
  try {
    const mailOptions = {
      from: '"OnyxHooks & More™ Team" <info@onyxnpearls.com>',
      replyTo: 'info@onyxnpearls.com',
      to: recipientEmail,
      subject: `🏆 Welcome to the Vault Elite - Exclusive Access Activated`,
      html: `
        <div style="max-width: 600px; margin: 0 auto; background: linear-gradient(135deg, #6b46c1 0%, #8b5cf6 100%); color: white; font-family: Arial, sans-serif;">
          <div style="padding: 40px 30px; text-align: center;">
            <h1 style="margin: 0 0 20px 0; font-size: 28px;">🏆 Welcome to the Vault Elite</h1>
            <div style="width: 120px; height: 120px; border-radius: 50%; border: 4px solid #FFD700; margin: 20px auto; background: rgba(255,215,0,0.2); display: flex; align-items: center; justify-content: center; font-size: 48px;">👑</div>
            <h2 style="margin: 20px 0; color: #FFD700;">Exclusive Elite Status Activated</h2>
            <p style="font-size: 18px; line-height: 1.6; margin: 20px 0;">
              ${customerName}, you've joined the most exclusive tier of creators. Your Vault Elite membership grants you access to our most powerful tools and direct Council access.
            </p>
            <div style="background: rgba(255,255,255,0.1); padding: 20px; border-radius: 10px; margin: 30px 0;">
              <h3 style="margin: 0 0 15px 0; color: #FFD700;">Your Vault Elite Benefits:</h3>
              <ul style="text-align: left; margin: 0; padding-left: 20px;">
                <li>Unlimited everything across all tools</li>
                <li>Direct AI Council member access</li>
                <li>Private intensives and custom training</li>
                <li>Campaign intelligence and analytics</li>
                <li>Priority support and feature requests</li>
                <li>Quarterly strategy sessions</li>
              </ul>
            </div>
            <a href="https://2a4f613c-1b0c-4dab-90a9-79a7fe4a7759-00-221njkuiufget.picard.replit.dev/dashboard" style="display: inline-block; background: #FFD700; color: #333; padding: 15px 30px; text-decoration: none; border-radius: 25px; font-weight: bold; margin: 20px 0;">Access Your Vault Dashboard</a>
            <p style="font-size: 14px; margin-top: 30px; opacity: 0.8;">
              Questions? Direct access: info@onyxnpearls.com<br>
              <strong>Since there's more to fishing than just hooks™</strong>
            </p>
          </div>
        </div>
      `,
      text: `🏆 Welcome to the Vault Elite

${customerName}, you've joined the most exclusive tier of creators. Your Vault Elite membership grants you access to our most powerful tools and direct Council access.

Your Vault Elite Benefits:
- Unlimited everything across all tools
- Direct AI Council member access
- Private intensives and custom training
- Campaign intelligence and analytics
- Priority support and feature requests
- Quarterly strategy sessions

Access Your Vault Dashboard: https://2a4f613c-1b0c-4dab-90a9-79a7fe4a7759-00-221njkuiufget.picard.replit.dev/dashboard

Questions? Direct access: info@onyxnpearls.com

Since there's more to fishing than just hooks™`
    };

    const result = await transporter.sendMail(mailOptions);
    logEmailResult('vault-confirmation-email', result);
    console.log('Vault confirmation email sent successfully:', result.messageId);
    return { success: true, messageId: result.messageId };
  } catch (error) {
    logEmailResult('vault-confirmation-email', null, error);
    console.error('SendGrid Vault Confirmation Email Error:', error);
    return { success: false, error: (error as Error).message || 'Failed to send vault confirmation email' };
  }
}

// Test email connectivity with enhanced logging
export async function testEmailConnection(): Promise<{ connected: boolean; message: string }> {
  try {
    await transporter.verify();
    const message = 'SendGrid SMTP connection verified successfully';
    console.log(`[${new Date().toISOString()}] ${message}`);
    return { connected: true, message };
  } catch (error) {
    const errorMessage = `SendGrid SMTP connection failed: ${(error as Error).message}`;
    console.error(`[${new Date().toISOString()}] ${errorMessage}`, {
      error: (error as Error).message,
      stack: (error as Error).stack
    });
    return { connected: false, message: errorMessage };
  }
}